/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ConfigGetReq;
import io.swagger.model.ConfigGetRes;
import io.swagger.model.ConfigGetdocwatermarkconfigRes;
import io.swagger.model.ConfigGetoemconfigbysectionReq;
import io.swagger.model.ConfigGetoemconfigbysectionRes;
import io.swagger.model.Error;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-09-10T06:15:45.348Z[GMT]")
@Api(value = "config", description = "the config API")
public interface ConfigApi {

    @ApiOperation(value = "获取配置信息", nickname = "configGetPost", notes = "", response = ConfigGetRes.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "配置管理", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功", response = ConfigGetRes.class),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/config/get",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ConfigGetRes> configGetPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody ConfigGetReq body
);


    @ApiOperation(value = "获取文件水印配置信息", nickname = "configGetdocwatermarkconfigPost", notes = "", response = ConfigGetdocwatermarkconfigRes.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "配置管理", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功", response = ConfigGetdocwatermarkconfigRes.class),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/config/getdocwatermarkconfig",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ConfigGetdocwatermarkconfigRes> configGetdocwatermarkconfigPost();


    @ApiOperation(value = "获取OEM配置信息", nickname = "configGetoemconfigbysectionPost", notes = "", response = ConfigGetoemconfigbysectionRes.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "配置管理", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功", response = ConfigGetoemconfigbysectionRes.class),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/config/getoemconfigbysection",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ConfigGetoemconfigbysectionRes> configGetoemconfigbysectionPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody ConfigGetoemconfigbysectionReq body
);

}

