/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import io.swagger.model.MessageGetReq;
import io.swagger.model.MessageGetRes;
import io.swagger.model.MessageRead2Req;
import io.swagger.model.MessageSendmailReq;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-09-10T06:15:45.348Z[GMT]")
@Api(value = "message", description = "the message API")
public interface MessageApi {

    @ApiOperation(value = "获取消息通知", nickname = "messageGetPost", notes = "", response = MessageGetRes.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "消息通知", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功", response = MessageGetRes.class),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/message/get",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<MessageGetRes> messageGetPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody MessageGetReq body
);


    @ApiOperation(value = "确认消息通知", nickname = "messageRead2Post", notes = "", authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "消息通知", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功"),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/message/read2",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> messageRead2Post(@ApiParam(value = "" ,required=true )  @Valid @RequestBody MessageRead2Req body
);


    @ApiOperation(value = "邮件发送", nickname = "messageSendmailPost", notes = "使用SMTP服务器发送邮件", authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "消息通知", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功"),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/message/sendmail",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> messageSendmailPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody MessageSendmailReq body
);

}

