/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import io.swagger.model.Perm2GetReq;
import io.swagger.model.Perm2GetRes;
import io.swagger.model.Perm2SetReq;
import io.swagger.model.Perm2SetRes;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-09-10T06:15:45.348Z[GMT]")
@Api(value = "perm2", description = "the perm2 API")
public interface Perm2Api {

    @ApiOperation(value = "获取权限配置", nickname = "perm2GetPost", notes = "", response = Perm2GetRes.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "权限管理", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功", response = Perm2GetRes.class),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/perm2/get",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Perm2GetRes> perm2GetPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Perm2GetReq body
);


    @ApiOperation(value = "设置权限配置", nickname = "perm2SetPost", notes = "", response = Perm2SetRes.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "权限管理", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功", response = Perm2SetRes.class),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/perm2/set",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Perm2SetRes> perm2SetPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Perm2SetReq body
);

}

