/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import io.swagger.model.PkiAuthenReq;
import io.swagger.model.PkiAuthenRes;
import io.swagger.model.PkiOriginalRes;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-09-10T06:15:45.348Z[GMT]")
@Api(value = "pki", description = "the pki API")
public interface PkiApi {

    @ApiOperation(value = "使用PKI认证", nickname = "pkiAuthenPost", notes = "", response = PkiAuthenRes.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "PKI认证", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功", response = PkiAuthenRes.class),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/pki/authen",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<PkiAuthenRes> pkiAuthenPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody PkiAuthenReq body
);


    @ApiOperation(value = "获取original", nickname = "pkiOriginalPost", notes = "", response = PkiOriginalRes.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "PKI认证", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功", response = PkiOriginalRes.class),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/pki/original",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<PkiOriginalRes> pkiOriginalPost();

}

