/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import io.swagger.model.UpdateCheckReq;
import io.swagger.model.UpdateCheckRes;
import io.swagger.model.UpdateDownloadReq;
import io.swagger.model.UpdateDownloadRes;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-09-10T06:15:45.348Z[GMT]")
@Api(value = "update", description = "the update API")
public interface UpdateApi {

    @ApiOperation(value = "检查客户端是否需要更新", nickname = "updateCheckPost", notes = "", response = UpdateCheckRes.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "客户端检查更新", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功", response = UpdateCheckRes.class),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/update/check",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<UpdateCheckRes> updateCheckPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody UpdateCheckReq body
);


    @ApiOperation(value = "下载客户端升级包", nickname = "updateDownloadPost", notes = "", response = UpdateDownloadRes.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "客户端检查更新", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "接口调用成功", response = UpdateDownloadRes.class),
        @ApiResponse(code = 400, message = "接口调用失败，HTTP状态码可能为4xx、5xx，具体参见错误码说明章节", response = Error.class) })
    @RequestMapping(value = "/update/download",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<UpdateDownloadRes> updateDownloadPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody UpdateDownloadReq body
);

}

